### ISSUE TITLE
Uncaught TypeError: Cannot read property 'URI' of null

### ISSUE THREAD

**Issue by soredake** [js-padavan/atom-enhanced-tabs#17]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.16
**System**: Mac OS X 10.10.5
**Thrown From**: [enhanced-tabs](https://github.com/js-padavan/atom-enhanced-tabs) package, v1.3.2
### Stack Trace

Uncaught TypeError: Cannot read property 'URI' of null

```
At /Users/susekaboss/Documents/github/home/.atom/packages/enhanced-tabs/lib/enhanced-tabs.coffee:98

TypeError: Cannot read property 'URI' of null
  at Object.module.exports.EnhancedTabs.addToOpenedTabs (/Users/susekaboss/Documents/github/home/.atom/packages/enhanced-tabs/lib/enhanced-tabs.coffee:63:36)
  at /Users/susekaboss/Documents/github/home/.atom/packages/enhanced-tabs/lib/enhanced-tabs.coffee:52:8
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/Resources/app.asar/src/pane-container.js:320:34
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/Resources/app.asar/src/pane.js:250:22)
  at Pane.module.exports.Pane.activateItem (/opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/Resources/app.asar/src/pane.js:314:21)
  at tabs-tab.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
  2x -0:09.9.0 enhanced-tabs:toggle (div.image-view)
```
### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "projectHome": "~/Documents/github",
    "ignoredNames": [
      ".git",
      ".DS_STORE",
      ".idea"
    ],
    "disabledPackages": [
      "metrics",
      "quick-jump",
      "javascript-snippets",
      "es6-javascript"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.2.1
color-picker, v2.0.12
devdocs, v0.2.1
editorconfig, v1.2.0
enhanced-tabs, v1.3.2
file-icons, v1.6.9
language-lua, v0.9.4
language-nginx, v0.6.0
linter, v1.6.0
linter-eslint, v3.0.2
linter-shellcheck, v1.0.1
linter-stylint, v2.0.1
minimap, v4.13.3
minimap-git-diff, v4.1.8
project-manager, v2.5.2
react-snippets, v0.2.0
smart-tab-name, v1.0.3
smart-tags, v0.1.0
ssh-config, v0.10.1

# Dev
No dev packages
```

**Comment by masics** [comment]
It is happening again now with a new update.
