### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getLongTitle' of undefined

### ISSUE THREAD

**Issue by dnswus** [js-padavan/atom-enhanced-tabs#2]
[Enter steps to reproduce below:]
1. Close all tabs

**Atom Version**: 0.174.0
**System**: Mac OS X 10.10.1
**Thrown From**: [enhanced-tabs](https://github.com/js-padavan/atom-enhanced-tabs) package, v1.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getLongTitle' of undefined

```
At /Users/dennis/.atom/packages/enhanced-tabs/lib/enhanced-tabs.coffee:37

TypeError: Cannot read property 'getLongTitle' of undefined
  at /Users/dennis/.atom/packages/enhanced-tabs/lib/enhanced-tabs.coffee:37:7
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:347:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:389:16)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:457:16)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:174:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/go-to-line/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/go-to-line/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```
### Commands

```
     -0:00.6 project-find:show (atom-text-editor.editor)
     -0:00.4 core:paste (atom-text-editor.editor.mini)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "sublime-tabs"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v1.1.0
circle-ci, v0.3.0
enhanced-tabs, v1.0.0
language-haml, v0.15.0
language-rspec, v0.2.1
minimap, v3.5.6
minimap-git-diff, v3.1.0
pretty-json, v0.3.2
seti-syntax, v0.2.1
seti-ui, v0.6.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by js-padavan** [comment]
Thank you for noticing. Update with bugfix now is availiable.
