### ISSUE TITLE
Failed to activate the enhanced-tabs package

### ISSUE THREAD

**Issue by noomz** [js-padavan/atom-enhanced-tabs#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [enhanced-tabs](https://github.com/js-padavan/atom-enhanced-tabs) package, v1.1.0
### Stack Trace

Failed to activate the enhanced-tabs package

```
At Cannot read property 'getLongTitle' of undefined

TypeError: Cannot read property 'getLongTitle' of undefined
  at Object.module.exports.EnhancedTabs.activate (/Users/siriwat/.atom/packages/enhanced-tabs/lib/enhanced-tabs.coffee:16:20)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:742:29
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:227:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:159:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:75:30)
  at EventEmitter.emit (events.js:116:17)

```
### Commands

```
  5x -9:49.7 pane:show-next-item (div.settings-view.pane-item)
  2x -9:40.0 tree-view:toggle (atom-text-editor.editor.is-focused)
  3x -9:00.9 core:close (atom-text-editor.editor.is-focused)
     -5:41.3 core:confirm (atom-text-editor.editor.mini)
  8x -2:12.7 tree-view:toggle (div.settings-view.pane-item)
     -0:01.8 enhanced-tabs:toggle (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      "node_modules",
      ".tmp",
      ".sass-cache",
      "bower_components"
    ],
    "disabledPackages": [
      "autoclose-html",
      "html-helper",
      "atom-jshint",
      "styleguide",
      "dev-live-reload",
      "glist",
      "metrics",
      "welcome",
      "geojson-preview",
      "background-tips",
      "deprecation-cop",
      "devdocs",
      "django-templates",
      "open-on-github",
      "package-generator",
      "spell-check",
      "project-manager",
      "tabs",
      "tree-view"
    ],
    "projectHome": "/Users/siriwat/Projects",
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.1.0
atom-jinja2, v0.5.0
atom-lint, v0.20.1
auto-detect-indentation, v0.3.0
better-handlebars, v0.1.1
color-picker, v1.4.4
editorconfig, v0.3.0
enhanced-tabs, v1.1.0
git-tab-status, v1.5.3
language-ejs, v0.1.0
language-groovy, v0.3.0
language-python-django-templates, v0.1.0
language-varnish, v0.3.0
linter, v0.12.0
project-colorize, v0.1.0
project-ring, v0.19.6
seti-syntax, v0.3.3
status-tab-spacing, v0.3.1
sublime-tabs, v0.5.0
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

**Comment by j5lx** [comment]
Same here.

**Comment by moohkooh** [comment]
Here also.

**Comment by martinruenz** [comment]
Had the same issue. 
I was searching for a package to go to the last tabs using ctrl-tab. Since I couldn't find a working package I implemented a very basic one myself. In case somebody is searching for this functionality: https://atom.io/packages/ctrl-last-tab (pull-requests welcome)

**Comment by jerone** [comment]
Got this error when pressing <kbd>Ctrl</kbd>+<kbd>Tab</kbd>.

---

**Atom Version**: 1.0.0
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [enhanced-tabs](https://github.com/js-padavan/atom-enhanced-tabs) package, v1.3.0

### Stack Trace

Failed to activate the enhanced-tabs package

```
At Cannot read property 'getLongTitle' of undefined

TypeError: Cannot read property 'getLongTitle' of undefined
  at Object.module.exports.EnhancedTabs.activate (C:\Users\jerone\.atom\packages\enhanced-tabs\lib\enhanced-tabs.coffee:17:20)
  at Package.module.exports.Package.activateNow (C:\Users\jerone\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:240:19)
  at C:\Users\jerone\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:772:25
  at Emitter.module.exports.Emitter.emit (C:\Users\jerone\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\jerone\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:222:20)
  at C:\Users\jerone\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\jerone\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\jerone\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\jerone\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:180:20)

```

### Commands

```
     -0:59 settings-view:view-installed-packages (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
     -0:55.2.0 enhanced-tabs:toggle (div.settings-view.pane-item)
```

### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
about, v0.5.0
color-picker, v2.0.7
editorconfig, v1.0.0
enhanced-tabs, v1.3.0
expose, v0.2.0
file-icons, v1.5.8
flex-tool-bar, v0.4.2
foldername-tabs, v0.1.1
gutter-shadow, v0.5.0
indentation-indicator, v0.6.0
language-jade, v0.4.0
language-sln, v0.1.0
linter, v1.1.0
linter-coffeelint, v0.3.2
markdown-scroll-sync, v0.4.0
menu-manager, v0.4.2
minimap, v4.10.1
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-selection, v4.3.0
new-tab, v0.3.0
open-recent, v2.2.4
project-view, v0.1.2
soft-wrap-indicator, v0.7.0
spell-check, v0.59.0
symbols-tree-view, v0.9.3
tool-bar, v0.1.8
travis-ci-status, v0.15.1
useful-context-menu, v0.2.1
```

**Comment by fpauser** [comment]
Same problem here...

atom-1.0.3 on ubuntu 14.04 (64bit)

Error: Cannot read property 'getLongTitle' of undefined

Stacktrace:

```
TypeError: Cannot read property 'getLongTitle' of undefined
  at Object.module.exports.EnhancedTabs.activate (/home/fpauser/.atom/packages/enhanced-tabs/lib/enhanced-tabs.coffee:17:20)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:243:19)
  at /usr/share/atom/resources/app.asar/src/package.js:792:25
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:222:20)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)
```

**Comment by fpauser** [comment]
I just discovered that this only happens when the "Settings" tab is active when the initial <kbd>ctrl</kbd>+<kbd>tab</kbd> in a editing-session is fired. 

Reproduce:
Deacticate the "enhanced-tabs" package and activate again. Fire the initial <kbd>ctrl</kbd>+<kbd>tab</kbd> while being on the "Settings" tab. -> ERROR

Work araound:
Deacticate the "enhanced-tabs" package and activate again. Before fireing the inital <kbd>ctrl</kbd>+<kbd>tab</kbd> change tab to a "normal", non-"Settings" tab. -> SUCCESS

Somehow the "Settings"-tab seems to behave different. Also note, that there is no "Settings"-entry in the tabs-lis. Instead one of the other tabs is listed twice.

**Comment by jkw** [comment]
Just tried what @fpauser recommended as work around, worked like a charm.
